(() => {
  'use strict'
  const $ = (s) => document.querySelector(s), $$ = (s) => [...document.querySelectorAll(s)]
  const key = 'calling-notes-users'
  const demo = { id: crypto.randomUUID(), imgSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80', fullName: 'Rahul David', hometown: 'Auckland', purpose: 'Quick ecommerce talk', category: 'urgent', mobileNo: '+1234567890', emailAddr: 'rahul.david@example.com', whatsappNo: '+1234567890', linkedInUrl: 'https://linkedin.com', instagramUrl: 'https://instagram.com', xUrl: 'https://x.com' }
  let users; try { users = JSON.parse(localStorage.getItem(key)) || JSON.parse(localStorage.getItem('users')) } catch { users = null }; users = Array.isArray(users) && users.length ? users.map((u) => ({ ...u, id: u.id || crypto.randomUUID() })) : [demo]
  let filter = 'all', selected = null
  const safe = (x = '') => String(x).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c])
  const number = (x, plus = false) => String(x || '').replace(plus ? /[^\d+]/g : /\D/g, '')
  const save = () => localStorage.setItem(key, JSON.stringify(users))
  const filtered = () => filter === 'all' ? users : users.filter((u) => u.category === filter)
  const link = (href, icon, label) => href ? `<a href="${safe(href)}" target="_blank" rel="noopener noreferrer" aria-label="${label}"><i class="fa-brands ${icon}"></i></a>` : ''
  function makeCard(u) { const social = link(u.whatsappNo && `https://wa.me/${number(u.whatsappNo)}`, 'fa-whatsapp', 'WhatsApp') + link(u.linkedInUrl, 'fa-linkedin', 'LinkedIn') + link(u.instagramUrl, 'fa-instagram', 'Instagram') + link(u.xUrl, 'fa-x-twitter', 'X'); return `<article class="card-box ${selected === u.id ? 'selected' : ''}" data-id="${u.id}" tabindex="0"><div class="card"><header class="card-header"><img class="profile-pic" src="${safe(u.imgSrc)}" alt="${safe(u.fullName)}"><div><h2 class="name">${safe(u.fullName)}</h2><span class="priority-badge ${u.category}">${u.category === 'norush' ? 'No rush' : safe(u.category)}</span></div></header><div class="card-desc"><div><p class="tag">Home town</p><p class="val">${safe(u.hometown)}</p></div><div><p class="tag">Purpose</p><p class="val">${safe(u.purpose)}</p></div><footer class="card-actions">${u.mobileNo ? `<a class="call-btn" href="tel:${number(u.mobileNo, true)}"><i class="fa-solid fa-phone"></i> Call</a>` : ''}${u.emailAddr ? `<a class="mail-btn" href="mailto:${encodeURIComponent(u.emailAddr)}"><i class="fa-regular fa-envelope"></i> Mail</a>` : ''}<div class="social-media">${social}</div></footer></div></div></article>` }
  function render() { const visible = filtered(); $('.cards-container').innerHTML = visible.map(makeCard).join(''); $('.empty-state').hidden = !!visible.length; $('.card-count').textContent = `${visible.length} ${visible.length === 1 ? 'note' : 'notes'}`; $('.delete').disabled = !selected }
  function select(id) { selected = id; render() }
  function rotate(dir) { const visible = filtered(); if (visible.length < 2) return; const current = visible.findIndex((u) => u.id === (selected || visible[0].id)); const picked = visible[(current + dir + visible.length) % visible.length]; selected = picked.id; users = users.filter((u) => u.id !== picked.id); dir > 0 ? users.push(picked) : users.unshift(picked); save(); render() }
  function tab(name) { $$('.tab-btn').forEach((b) => b.classList.toggle('active', b.dataset.tab === name)); $$('.form-section').forEach((s) => s.classList.toggle('active', s.classList.contains(name))); $('.next-section').hidden = name === 'contact'; $('.create-note').hidden = name !== 'contact' }
  function modal(open) { $('.form-container').classList.toggle('active', open); $('.form-container').setAttribute('aria-hidden', !open); if (!open) { $('#callForm').reset(); $('#error-message').textContent = ''; tab('client') } }
  $('.cards-container').addEventListener('click', (e) => { const c = e.target.closest('.card-box'); if (c && !e.target.closest('a')) select(c.dataset.id) })
  $('.cards-container').addEventListener('keydown', (e) => { if ((e.key === 'Enter' || e.key === ' ') && e.target.matches('.card-box')) { e.preventDefault(); select(e.target.dataset.id) } })
  $('.add').onclick = () => modal(true); $$('.close').forEach((b) => b.onclick = () => modal(false)); $('.form-container').onclick = (e) => { if (e.target === $('.form-container')) modal(false) }; $('.up').onclick = () => rotate(1); $('.down').onclick = () => rotate(-1)
  $('.delete').onclick = () => { if (!selected) return; users = users.filter((u) => u.id !== selected); selected = null; save(); render() }
  $('#priority-filter').onchange = (e) => { filter = e.target.value; selected = null; render() }
  $$('.view-btn').forEach((b) => b.onclick = () => { document.body.dataset.view = b.dataset.view; $$('.view-btn').forEach((x) => x.classList.toggle('active', x === b)); $('.app-nav').classList.remove('menu-open'); $('.menu-toggle').setAttribute('aria-expanded', 'false') })
  $('.theme-toggle').onclick = () => document.body.classList.toggle('dark-theme'); $('.menu-toggle').onclick = () => { const open = $('.app-nav').classList.toggle('menu-open'); $('.menu-toggle').setAttribute('aria-expanded', open) }; $$('.tab-btn').forEach((b) => b.onclick = () => tab(b.dataset.tab)); $('.next-section').onclick = () => tab('contact')
  $('#callForm').onsubmit = (e) => { e.preventDefault(); const value = (id) => $(id).value.trim(), image = value('#imageurl'), name = value('#fullname'), town = value('#hometown'), purpose = value('#purpose'), mobile = value('#mobile-no'), email = value('#email-address'), whatsapp = value('#whatsapp-no'); const fail = (message, section) => { $('#error-message').textContent = message; tab(section) }; if (!image || !name || !town || !purpose) return fail('Complete all client details.', 'client'); try { new URL(image) } catch { return fail('Enter a valid image URL.', 'client') } if (!/^\+?[\d\s()-]{7,15}$/.test(mobile)) return fail('Enter a valid mobile number.', 'contact'); if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return fail('Enter a valid email address.', 'contact'); const url = (value, site) => !value ? '' : /^https?:\/\//.test(value) ? value : `https://${site}.com/${value.replace(/^@/, '').replace(`${site}.com/`, '')}`; users.unshift({ id: crypto.randomUUID(), imgSrc: image, fullName: name, hometown: town, purpose, category: value('#category'), mobileNo: mobile, emailAddr: email, whatsappNo: whatsapp || mobile, linkedInUrl: url(value('#linkedIn-id'), 'linkedin'), instagramUrl: url(value('#instagram-handle'), 'instagram'), xUrl: url(value('#x-handle'), 'x') }); filter = 'all'; $('#priority-filter').value = 'all'; save(); modal(false); render() }
  render()
})()
